### ISSUE TITLE
phpmyadmin-cf fails to install: Composer could not find a composer.json

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/phpmyadmin-cf#2]
phpmyadmin-cf fails to install: Composer could not find a composer.json

Is the cf-ready.zip outdated/corrupted ? 

```
$ wget https://github.com/cloudfoundry-community/phpmyadmin-cf/archive/cf-ready.zip
--2015-07-29 12:22:23--  https://github.com/cloudfoundry-community/phpmyadmin-cf/archive/cf-ready.zip
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/cloudfoundry-community/phpmyadmin-cf/zip/cf-ready [following]
--2015-07-29 12:22:24--  https://codeload.github.com/cloudfoundry-community/phpmyadmin-cf/zip/cf-ready
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: `cf-ready.zip'

    [                                                                              <=>          ] 16,224,922   706K/s   in 23s

2015-07-29 12:22:48 (696 KB/s) - `cf-ready.zip' saved [16224922]


$ cf push phpmyadmin -p cf-ready.zip  -n [...]
Updating app phpmyadmin in org orange / space api-dsif as gberche...
OK

Creating route [...]
OK

Binding ...
OK

Uploading phpmyadmin...
Uploading app files from: cf-ready.zip
Uploading 13M, 3098 files
Done uploading
OK

Starting app phpmyadmin in org orange / space [...] as gberche...
-----> Downloaded app package (16M)
-------> Buildpack version 3.2.1
Installing HTTPD
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1534k  100 1534k    0     0  18.8M      0 --:--:-- --:--:-- --:--:-- 18.8M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14682  100 14682    0     0  1068k      0 --:--:-- --:--:-- --:--:-- 1068k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_unixd-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19969  100 19969    0     0  1205k      0 --:--:-- --:--:-- --:--:-- 1205k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_setenvif-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  137k  100  137k    0     0  4364k      0 --:--:-- --:--:-- --:--:-- 4364k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_proxy-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16787  100 16787    0     0  1291k      0 --:--:-- --:--:-- --:--:-- 1291k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_dir-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20550  100 20550    0     0  1175k      0 --:--:-- --:--:-- --:--:-- 1175k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_reqtimeout-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42000  100 42000    0     0  2555k      0 --:--:-- --:--:-- --:--:-- 2555k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_log_config-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28927  100 28927    0     0  46.6M      0 --:--:-- --:--:-- --:--:-- 46.6M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_authz_core-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25276  100 25276    0     0  1845k      0 --:--:-- --:--:-- --:--:-- 1845k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_mime-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31561  100 31561    0     0  2775k      0 --:--:-- --:--:-- --:--:-- 2775k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_proxy_fcgi-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17805  100 17805    0     0  1166k      0 --:--:-- --:--:-- --:--:-- 1166k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_remoteip-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13323  100 13323    0     0  6390k      0 --:--:-- --:--:-- --:--:-- 6390k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_env-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72297  100 72297    0     0  5386k      0 --:--:-- --:--:-- --:--:-- 5386k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_mpm_event-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82878  100 82878    0     0  11.4M      0 --:--:-- --:--:-- --:--:-- 11.4M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_rewrite-2.4.12.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16145  100 16145    0     0  20.6M      0 --:--:-- --:--:-- --:--:-- 20.6M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/httpd/2.4.12/httpd-mod_authz_host-2.4.12.tar.gz] to [/tmp]
Installing PHP
PHP 5.5.23
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5000k  100 5000k    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 12.8M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   99k  100   99k    0     0  2636k      0 --:--:-- --:--:-- --:--:-- 2636k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-pdo_mysql-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40267  100 40267    0     0   617k      0 --:--:-- --:--:-- --:--:--  617k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-bz2-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  327k  100  327k    0     0  11.1M      0 --:--:-- --:--:-- --:--:-- 11.1M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-zip-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8640k  100 8640k    0     0  18.6M      0 --:--:-- --:--:-- --:--:-- 18.6M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-fpm-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61890  100 61890    0     0  36.2M      0 --:--:-- --:--:-- --:--:-- 36.2M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-zlib-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  170k  100  170k    0     0  4771k      0 --:--:-- --:--:-- --:--:-- 4771k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-openssl-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  163k  100  163k    0     0  28.8M      0 --:--:-- --:--:-- --:--:-- 28.8M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-pdo-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  455k  100  455k    0     0  7944k      0 --:--:-- --:--:-- --:--:-- 7944k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-gd-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1046k  100 1046k    0     0  14.0M      0 --:--:-- --:--:-- --:--:-- 44.7M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-mbstring-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  130k  100  130k    0     0  82.9M      0 --:--:-- --:--:-- --:--:-- 82.9M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-mcrypt-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  250k  100  250k    0     0  3653k      0 --:--:-- --:--:-- --:--:-- 3653k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-mysqli-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  109k  100  109k    0     0  5625k      0 --:--:-- --:--:-- --:--:-- 5625k
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-curl-5.5.23.tar.gz] to [/tmp]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8486k  100 8486k    0     0  29.5M      0 --:--:-- --:--:-- --:--:-- 33.3M
Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-cli-5.5.23.tar.gz] to [/tmp]

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

TIP: use 'cf.exe logs phpmyadmin --recent' for more information

$ cf.exe logs phpmyadmin --recent
[...]
2015-07-29T12:25:45.09+0200 [STG/0]      OUT Installing PHP
2015-07-29T12:25:45.10+0200 [STG/0]      OUT PHP 5.5.23
2015-07-29T12:25:45.26+0200 [STG/0]      ERR   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2015-07-29T12:25:45.26+0200 [STG/0]      ERR                                  Dload  Upload   Total   Spent    Left  Speed
100 5000k  100 5000k    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 12.8M
2015-07-29T12:25:45.66+0200 [STG/0]      OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/php/5.5.23/php-5.5.23.tar.gz] to [/tmp]
2015-07-29T12:25:46.06+0200 [STG/0]      ERR   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2015-07-29T12:25:46.06+0200 [STG/0]      ERR                                  Dload  Upload   Total   Spent    Left  Speed
100   99k  100   99k    0     0  2636k      0 --:--:-- --:--:-- --:--:-- 2636k

[...]
2015-07-29T12:25:50.46+0200 [STG/0]      OUT Downloaded [https://pivotal-buildpacks.s3.amazonaws.com/php/binaries/trusty/composer/1.0.0-alpha10/composer.phar] to [/tmp]
2015-07-29T12:25:50.68+0200 [STG/0]      OUT PROTIP: Include a `composer.lock` file with your application! This will make sure the exact same version of dependencies are used when you deploy to CloudFoundry.
2015-07-29T12:25:50.80+0200 [STG/0]      ERR Composer could not find a composer.json file in /tmp/staged/app
2015-07-29T12:25:50.80+0200 [STG/0]      ERR To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section
2015-07-29T12:25:50.81+0200 [STG/0]      OUT -----> Composer command failed
2015-07-29T12:25:50.81+0200 [STG/0]      ERR Traceback (most recent call last):
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/scripts/compile.py", line 51, in <module>
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     .from_build_pack('lib/additional_commands')
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/lib/build_pack_utils/builder.py", line 189, in extensions
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     process_extension(path, ctx, 'compile', process, args=[self])
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/lib/build_pack_utils/utils.py", line 69, in process_extension
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/extensions/composer/extension.py", line 400, in compile
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     return composer.compile(install)
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/lib/extension_helpers.py", line 154, in compile
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     self._compile(install)
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/extensions/composer/extension.py", line 164, in _compile
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     self.run()
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/extensions/composer/extension.py", line 285, in run
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     *self._ctx['COMPOSER_INSTALL_OPTIONS'])
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/extensions/composer/extension.py", line 330, in run
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     shell=True)
2015-07-29T12:25:50.81+0200 [STG/0]      ERR   File "/var/vcap/data/dea_next/admin_buildpacks/4c9892e5-9645-4375-a9c9-91817de9e14a_bca21b65d5f983c23402fd35154b5b4fa8121965/lib/build_pack_utils/runner.py", line 109, in stream_output
2015-07-29T12:25:50.81+0200 [STG/0]      ERR     raise CalledProcessError(retcode, cmd)
2015-07-29T12:25:50.81+0200 [STG/0]      ERR build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7f1dcddb1780>' returned non-zero exit status 1
2015-07-29T12:25:50.83+0200 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-07-29T12:25:50.96+0200 [API/0]      ERR encountered error: App staging failed in the buildpack compile phase
```

Same issue with PHP buildpack 3.3.0.

**Comment by ArthurHlt** [comment]
Hello,
please unzip the the file before pushing on Cloud Foundry

**Comment by gberche-orange** [comment]
Thanks @ArthurHlt. Sorry I missed that in the docs. 

May be an improvement suggestion would be to have the release zip include the app at its root instead of a "phpmyadmin-cf-cf-ready" subfolder. Since Cf supports pushing archives directly this would remove one manual step to deploy  phpmyadmin-cf

**Comment by ArthurHlt** [comment]
I actually can't do that cause the zip file that you download is bundled by github.
The link that I provide is the same link given by the `Download ZIP` button on the side bar.
