### ISSUE TITLE
Upgrade to php 5.6 buildpack

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry-community/phpmyadmin-cf#5]
Recent versions of Pivotal Cloud Foundry have upgraded to php 5.6 build pack.  To work around on new versions of PCF you can do the following:

cf push mysql-admin -b https://github.com/cloudfoundry/php-buildpack#v4.3.27

Take note in the warning that any build pack released after 2016-07-21 will not support php 5.5.

**Comment by ArthurHlt** [comment]
Thank you for your contribution but I don't get what is the problem, this is not tied to a buildpack version.

**Comment by xyloman** [comment]
Thanks for the quick response.  I should have included the stack trace that I received on PCF 1.10:
`Staging...
-------> Buildpack version 4.3.31
WARNING: PHP version 5.5.* not available, using default version (5.6.30). In future versions of the buildpack, specifying a non-existent PHP version will cause staging to fail. See: http://docs.cloudfoundry.org/buildpacks/php/gsg-php-composer.html
Installing HTTPD
HTTPD 2.4.25
Downloaded [file:///tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/dependencies/https___buildpacks.cloudfoundry.org_dependencies_httpd_httpd-2.4.25-linux-x64-bf8851c4.tgz] to [/tmp]
Installing PHP
PHP 5.6.30
Downloaded [file:///tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.30-linux-x64-13625eaa.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/dependencies/https___buildpacks.cloudfoundry.org_dependencies_php_php-5.6.30-linux-x64-13625eaa.tgz] to [/tmp]
Downloaded [file:///tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/dependencies/https___buildpacks.cloudfoundry.org_dependencies_composer_composer-1.4.1-0eedfb38.phar] to [/tmp]
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - This package requires php 5.5.* but your PHP version (5.6.30) does not satisfy that requirement.
-----> Composer command failed
Traceback (most recent call last):
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/scripts/compile.py", line 47, in <module>
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/lib/build_pack_utils/builder.py", line 208, in extensions
    process_extension(path, ctx, 'compile', process, args=[self])
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/lib/build_pack_utils/utils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/extensions/composer/extension.py", line 429, in compile
    return composer.compile(install)
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/lib/extension_helpers.py", line 154, in compile
    self._compile(install)
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/extensions/composer/extension.py", line 196, in _compile
    self.run()
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/extensions/composer/extension.py", line 331, in run
    *self._ctx['COMPOSER_INSTALL_OPTIONS'])
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/extensions/composer/extension.py", line 375, in run
    shell=True)
  File "/tmp/buildpacks/4533403b621e3151f0d9d6f50ef62a59/lib/build_pack_utils/runner.py", line 109, in stream_output
    raise CalledProcessError(retcode, cmd)
build_pack_utils.runner.CalledProcessError: Command '<open file '<fdopen>', mode 'w' at 0x7ff2c3337930>' returned non-zero exit status 2
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container
`

**Comment by ArthurHlt** [comment]
Thank you for details. `composer.json` was tied to a php version, this should be fixed now.
